name: travel_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints:
  flutter_secure_storage:
  bloc:
  flutter_bloc:
  equatable:
  http:
  flutter_svg:
  provider:
  flutter_localization:
  intl:
  json_annotation:
  shared_preferences:
  bloc_concurrency:
  image_picker: ^1.1.2
  qr_flutter:
  story_view: ^0.16.5
  google_maps_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/loaded.svg
    - img/login.svg
    - img/undraw_fans_re_cri3.svg
    - img/signup.svg
    - assets/map_style.json

fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
        weight: 700
      - asset: fonts/Roboto-Italic.ttf
        style: italic
      - asset: fonts/Roboto-BoldItalic.ttf
        weight: 700
        style: italic



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
